version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: xpaydb
  xpayapi:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    depends_on:
      - postgres
